In [1]:
import numpy as np

In [2]:
a = np.array([0,30,45,60,90])
a

array([ 0, 30, 45, 60, 90])

In [7]:
# sin of array
sin = np.sin(a*np.pi/180)
sin

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [5]:
# cos of array
np.cos(a*np.pi/180)  # this will help you to find cosin similarity b/w two vector

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [6]:
np.tan(a*np.pi/180)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [9]:
# compute inverse of angle, return radions
inv = np.arcsin(sin)
inv

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [10]:
# check the result by converting to degrees
np.degrees(inv)

array([ 0., 30., 45., 60., 90.])

In [12]:
a = np.array([1.6777,3.653,7])
np.round(a, decimals=1)

array([1.7, 3.7, 7. ])

In [13]:
a = np.array([1.6777,3.653,7])
np.floor(a)

array([1., 3., 7.])

In [14]:
np.ceil(a)

array([2., 4., 7.])